name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or whatever your default branch is

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows the action to push to the gh-pages branch
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or a newer version
          cache: 'npm'

      - name: Install Dependencies 📦
        run: npm install

      - name: Build 🏗️
        run: npm run build # This runs the build script from your package.json

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # The folder your build command created
